//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAutoGenNumber
    {
        public int AutoGenNumberId { get; set; }
        public string AutoGenNumberText { get; set; }
        public int AutoPrefixId { get; set; }
        public bool UsePrefix { get; set; }
        public int Start { get; set; }
        public int Stop { get; set; }
        public int StartFrom { get; set; }
        public bool AllowManual { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
