//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanRepayment
    {
        public int RepaymentId { get; set; }
        public int LoanId { get; set; }
        public int BankId { get; set; }
        public int CurrencyId { get; set; }
        public int SerialId { get; set; }
        public int BaseCurrencyId { get; set; }
        public decimal ExchangeRate { get; set; }
        public decimal ForeignAmount { get; set; }
        public decimal Amount { get; set; }
        public int RepaymentNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public System.DateTime ValueDate { get; set; }
        public int TransType { get; set; }
        public string PaymentMode { get; set; }
        public string VoucherNo { get; set; }
        public string DocumentNo { get; set; }
        public string PaidBy { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public byte[] Timestamp { get; set; }
        public System.Guid GUID { get; set; }
    }
}
