//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanGuarator
    {
        public int LoanGuarantorId { get; set; }
        public Nullable<int> LoanId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string FullName { get; set; }
        public string IdNo { get; set; }
        public Nullable<int> GuarantorTypeId { get; set; }
        public string LoanSerialRef { get; set; }
        public Nullable<decimal> GuaranteedAmount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public byte[] TimeStamp { get; set; }
        public System.Guid GUID { get; set; }
    }
}
