//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMember
    {
        public int MemberId { get; set; }
        public string Payroll { get; set; }
        public string MemberNo { get; set; }
        public string FullName { get; set; }
        public string SearchName { get; set; }
        public string IdNo { get; set; }
        public bool IsPerson { get; set; }
        public string NHIFNo { get; set; }
        public string KRAPin { get; set; }
        public string NSSFNo { get; set; }
        public string HudumaNo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int TitleId { get; set; }
        public string Gender { get; set; }
        public int MaritalStatusId { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNumber { get; set; }
        public string PhysicalLocation { get; set; }
        public string Address { get; set; }
        public string PostalAddress { get; set; }
        public int HierarchyId { get; set; }
        public int MemberStatusId { get; set; }
        public bool Blocked { get; set; }
        public decimal Gross { get; set; }
        public decimal Nett { get; set; }
        public int LevelofEducationId { get; set; }
        public int BusinessSectorId { get; set; }
        public int LevelofIncomeId { get; set; }
        public int ClientTypeId { get; set; }
        public int CompanyId { get; set; }
        public bool IsRegister { get; set; }
        public bool IsDormancy { get; set; }
        public string Remark { get; set; }
        public int SecurityQuestion { get; set; }
        public string RegistrationCode { get; set; }
        public int NationalityId { get; set; }
        public Nullable<System.DateTime> CompanyRegistrationDate { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string CompanyCertificateNo { get; set; }
        public int BankId { get; set; }
        public int BankBranchId { get; set; }
        public string BankAccountNo { get; set; }
        public int CurrencyId { get; set; }
        public string MachineName { get; set; }
        public string SecurityAnswer { get; set; }
        public System.DateTime SupervisedOn { get; set; }
        public string SupervisedBy { get; set; }
        public Nullable<decimal> TotalShares { get; set; }
        public Nullable<decimal> FreeShare { get; set; }
        public byte[] Timestamp { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
