//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestKin
    {
        public int KinId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string KinName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
